#Introduction

In [ ]:
print("Hello World")

Hello World


In [ ]:
import keyword
print(keyword.kwlist)
a=len(keyword.kwlist)
print(a)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
35


In [ ]:
 a=50
 b=50
 c=a+b
 print(c)

100


In [ ]:
x="hello"
x

'hello'

In [ ]:
l1=[1,2,3,4,5,6,7]
l1
for x in l1:
  print(x)
  len(l1)
l2=[8,9,10]

1
2
3
4
5
6
7


In [ ]:
l3=l1+l2
l3

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
l1=[1,1,1,2,2,2,3,3,3,4,4]
unique_elements = set(l1)
print(unique_elements)

{1, 2, 3, 4}


In [ ]:
for element in unique_elements:
  print(element)

1
2
3
4


In [ ]:
l2=[]
for x in l1:
  if x not in l2:
    l2.append(x)
l2

[1, 2, 3, 4]

In [ ]:
a=10
b=1.4
c='mani'

print(type(a))
print(type(b))
print(type(c))

<class 'int'>
<class 'float'>
<class 'str'>


In [ ]:
for x in range(1,10):
  print(x)

1
2
3
4
5
6
7
8
9


In [ ]:
#slicing
l1=[1,2,3,4,5,6,7,8,9,10]
print(l1[:6])

[1, 2, 3, 4, 5, 6]


In [ ]:
l1[-1]

10

In [ ]:
l1[::-1]

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [ ]:
l=input('enter a name ')
b=l[::-1]
if l==b:
  print('palindrome')
else:
  print('not palindrome')

enter a name lol
palindrome


In [ ]:
import random
numbers=[1,2,3,4,5,6,7,8,9,10]
random.shuffle(numbers)
print(numbers)

[6, 8, 1, 10, 9, 2, 3, 7, 5, 4]


In [ ]:
days=["monday","tuesday","wednesday","thursday", "friday","saturday","sunday"]
"wednesday" in days

True

In [ ]:
days=["monday","tuesday","wednesday","thursday", "friday","saturday","sunday"]
"wednesday"  not in days

False

In [ ]:
list=["red", "green", "blue", "yellow", "orange"]
print(list)
list.clear()
print(list)

['red', 'green', 'blue', 'yellow', 'orange']
[]


In [ ]:
nums=[1,2,3,4,1,4,2,1,7,8,1]
print(nums.count(1))

4


In [ ]:
list_1=[1,2,3,4,5]
print(list_1)
list_2=list_1.copy()
print(list_2)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


In [2]:
a=["a","b","c","d"]
print(a)
a.append("e")
print(a)

['a', 'b', 'c', 'd']
['a', 'b', 'c', 'd', 'e']


In [5]:
b=[1,2,3]
print(b.append(4))
print(b)

None
[1, 2, 3, 4]


In [6]:
list=["red", "green", "blue", "yellow", "orange"]
print(list)
list.clear()
print(list)

['red', 'green', 'blue', 'yellow', 'orange']
[]


In [7]:
nums=[1,2,3,4,1,4,2,1,7,8,1]
print(nums)
print(nums.count(1))

[1, 2, 3, 4, 1, 4, 2, 1, 7, 8, 1]
4


In [9]:
list_1=[1,2,3,4,5]
print(list_1)
list_2=list_1.copy()
print(list_2)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


In [12]:
A=[1,2,3,4,5]
B=[6,7,8,3,10]
print(A)
print(B)
A.extend(B)
print(A)

[1, 2, 3, 4, 5]
[6, 7, 8, 3, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 3, 10]


In [14]:
a=(5,)
print(type(a))
print(a)

<class 'tuple'>
(5,)


In [15]:
b=(1,2,3,4,5)
print(b)

(1, 2, 3, 4, 5)


In [16]:
c=(6.5,5.9,2.9)
print(c)

(6.5, 5.9, 2.9)


In [18]:
d=("one","two","three")
d

('one', 'two', 'three')

In [19]:
mix=("hello",709,8.9)
mix=("hello",709,8.9)
mix

('hello', 709, 8.9)

In [21]:
m=(1,2,3,4,"hello")
print(m[4])

hello


In [27]:
f={
    "name":"mani",
    "age":20,
    "education":"Engineer"
}
print(f)

{'name': 'mani', 'age': 20, 'education': 'Engineer'}


In [28]:
len(f)

3

In [29]:
type(f)

dict

In [30]:
x=f.keys()
x

dict_keys(['name', 'age', 'education'])

In [32]:
y=f.values()
y

dict_values(['mani', 20, 'Engineer'])

In [33]:
z=f.items()
z

dict_items([('name', 'mani'), ('age', 20), ('education', 'Engineer')])

In [35]:
set1={1,2,3,4,5}
print(set1)

{1, 2, 3, 4, 5}


In [36]:
set={1,2,3,4,5,7,1,1,5}
set

{1, 2, 3, 4, 5, 7}

In [38]:
len(set)

6

In [43]:
def add():
  a=2
  b=3
  sum=a+b
  return sum
add()
print(add())

5


In [45]:
import numpy as np
print(np.__version__)

1.26.4


In [47]:
import numpy as np

In [48]:
A1=np.array([1,2,3,4,5])
print(A1)

[1 2 3 4 5]


In [49]:
type( A1)

numpy.ndarray

In [51]:
A1.shape

(5,)

In [52]:
A1.size

5

In [54]:
#2d array
A2=np.array([[1,2,3],[4,5,6]])
print(A2)

[[1 2 3]
 [4 5 6]]


In [55]:
A2.shape

(2, 3)

In [57]:
type(A2)

numpy.ndarray

In [58]:
A2.size

6

In [59]:
A2.ndim

2

In [60]:
#3d array
A3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(A3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [61]:
A3.size

9

In [62]:
type(A3)

numpy.ndarray

In [63]:
A3.ndim

3

In [64]:
A3.shape

(1, 3, 3)

In [67]:
z1=np.zeros(4)
print(z1)

[0. 0. 0. 0.]


In [68]:
z1.shape

(4,)

In [70]:
z1=np.zeros(4,dtype=int)
(z1)

array([0, 0, 0, 0])

In [71]:
z1.shape

(4,)

In [72]:
z1.size

4

In [73]:
type(z1)

numpy.ndarray

In [74]:
z1.ndim

1

In [76]:
z2=np.zeros((3,4))
print(z2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [77]:
z2=np.zeros((3,4),dtype=int)
print(z2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [78]:
type(z2)

numpy.ndarray

In [79]:
z2.ndim

2

In [80]:
z2.shape

(3, 4)

In [81]:
z2.size

12

In [82]:
z3=np.zeros((3,4,2))
print(z3)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [83]:
z3.shape

(3, 4, 2)

In [85]:
z3.size

24

In [86]:
type(z3)

numpy.ndarray

In [87]:
z3.ndim

3

In [89]:
z3=np.zeros((2,3,4),dtype=int)
print(z3)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [90]:
type(z3)

numpy.ndarray

In [91]:
z3.shape

(2, 3, 4)

In [92]:
z3.size

24

In [93]:
z3.ndim

3

In [96]:
#1d ones array
import numpy as np
a1=np.ones(3)
(a1)

array([1., 1., 1.])

In [97]:
a1=np.ones(3,dtype=int)
(a1)

array([1, 1, 1])

In [98]:
type( a1)

numpy.ndarray

In [99]:
a1.size

3

In [100]:
a1.shape

(3,)

In [101]:
a1.ndim

1

In [103]:
#2d
a2=np.ones((3,4))
(a2)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [104]:
type(a2)

numpy.ndarray

In [105]:
a2.size

12

In [106]:
a2.shape

(3, 4)

In [107]:
a2.ndim

2

In [115]:
a2=np.ones((3,4),dtype=int)
a2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [117]:
a2.size

12

In [116]:
type(a2)

numpy.ndarray

In [118]:
a2.shape

(3, 4)

In [120]:
a2.ndim

2

In [121]:
#3d
a3=np.ones((4,2,3))
(a3)

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [122]:
type(a3)

numpy.ndarray

In [123]:
a3.size

24

In [124]:
a3.shape

(4, 2, 3)

In [125]:
a3.ndim

3

In [127]:
a3=np.ones((4,2,3),dtype=int)
a3

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [128]:
a3.size

24

In [129]:
a3.shape

(4, 2, 3)

In [130]:
a3.ndim

3

In [131]:
type(a3)

numpy.ndarray

In [132]:
#1d full array
f1=np.full(3,5)
f1

array([5, 5, 5])

In [133]:
f1=np.full(3,9,dtype=float)
f1

array([9., 9., 9.])

In [134]:
f1.shape

(3,)

In [135]:
f1.size

3

In [136]:
f1.ndim

1

In [137]:
type(f1)

numpy.ndarray

In [139]:
#2d full array
f2=np.full((2,3),9)
f2

array([[9, 9, 9],
       [9, 9, 9]])

In [140]:
#3d full array
f3=np.full((2,3,4),9)
f3

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [141]:
f3=np.full((2,3,4),9,dtype=float)
f3

array([[[9., 9., 9., 9.],
        [9., 9., 9., 9.],
        [9., 9., 9., 9.]],

       [[9., 9., 9., 9.],
        [9., 9., 9., 9.],
        [9., 9., 9., 9.]]])